--Phantom
if OBJECT_ID ('VIEW_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc VIEW_NHACHOTHUE_NHOMNHANVIEN
GO
create proc VIEW_NHACHOTHUE_NHOMNHANVIEN  
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION 
	SELECT *FROM NHACHOTHUE 
	WAITFOR DELAY '0:00:10'
COMMIT TRANSACTION
go

EXEC VIEW_NHACHOTHUE_NHOMNHANVIEN 

--Dirty Read
if OBJECT_ID ('VIEW_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc VIEW_NHABAN_NHOMNHANVIEN
GO
create proc VIEW_NHABAN_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	SELECT *FROM NHABAN 
COMMIT TRANSACTION
go

EXEC VIEW_NHABAN_NHOMNHANVIEN 

--Conversion-Deadlock
if OBJECT_ID ('ADD_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc ADD_NHABAN_NHOMNHANVIEN
GO
create PROC ADD_NHACHOTHUE_NHOMNHANVIEN
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@TIENTHUE1THANG INT,
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO NHACHOTHUE VALUES(@MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @TIENTHUE1THANG, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, 
@SOLUOTXEM)
	WAITFOR DELAY '0:00:15'
COMMIT TRANSACTION
go
EXEC ADD_NHACHOTHUE_NHOMNHANVIEN 'NT3', 'LN01', N'HÀ NỘI 3', 3, 'CNH03', 'NV03', 'CN03', 200000, '2019/12/20 00:00:00', '2020/12/20 00:00:00', 'TRỐNG', 3

--LostUpdate
if OBJECT_ID ('UPDATE_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_NHABAN_NHOMNHANVIEN
GO
create proc UPDATE_NHABAN_NHOMNHANVIEN 
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT,
	@GIABAN INT,
	@DIEUKIENBAN NVARCHAR(30)
AS
BEGIN TRANSACTION 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRY
	IF NOT EXISTS(SELECT  * FROM NHABAN WITH (Holdlock) WHERE MANHA = @MANHA )
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WITH (Holdlock) WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WITH (Holdlock) WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WITH (Holdlock) WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WITH (Holdlock) WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END

END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_NHABAN_NHOMNHANVIEN @MANHA
	EXEC ADD_NHABAN_NHOMNHANVIEN @MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, @SOLUOTXEM, @GIABAN, @DIEUKIENBAN
	WAITFOR DELAY '0:0:05'
COMMIT TRANSACTION
go

EXEC UPDATE_NHABAN_NHOMNHANVIEN 'N2', 'LN01', N'TP Hồ Chí Minh', 2, 'CN02', '003', 'CN01', '2018/10/15 00:00:00', '2019/10/15 00:00:00', 'TRỐNG', 3, 45000000, 'TRÊN 22T'

--Unrepeatable Read
if OBJECT_ID ('KIEMTRATINHTRANG_NHANVIEN','P') is not null
	drop proc KIEMTRATINHTRANG_NHANVIEN
GO
create proc KIEMTRATINHTRANG_NHANVIEN  
AS
BEGIN TRANSACTION 
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = 'NT1'AND TINHTRANG = N'Hết')
	PRINT N'NHÀ ĐÃ CHO THUÊ'
RETURN
 
COMMIT TRANSACTION
go

EXEC KIEMTRATINHTRANG_NHANVIEN