------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------PHÂN HỆ NHÂN VIÊN-----------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--1/
-- TÌM MÃ NHÀ TRONG BẢNG THÔNG BÁO XEM NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('FIND_MANHA_THONGBAOXEMNHA_NHOMNHANVIEN','P') is not null
	drop proc FIND_MANHA_THONGBAOXEMNHA_NHOMNHANVIEN
GO
create proc FIND_MANHA_THONGBAOXEMNHA_NHOMNHANVIEN  
	@MANHA CHAR(10)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM THONGBAOXEMNHA WHERE MANHABAN = @MANHA OR MANHATHUE = @MANHA)
	BEGIN
		PRINT N'MÃ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'MÃ NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT *FROM THONGBAOXEMNHA WHERE MANHABAN = @MANHA OR MANHATHUE = @MANHA
COMMIT TRANSACTION
go
--XEM BẢNG THÔNG BÁO XEM NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_TABLE_THONGBAOXEMNHA_NHOMNHANVIEN','P') is not null
	drop proc VIEW_TABLE_THONGBAOXEMNHA_NHOMNHANVIEN
GO
create proc VIEW_TABLE_THONGBAOXEMNHA_NHOMNHANVIEN
AS
BEGIN TRANSACTION 
SELECT *FROM THONGBAOXEMNHA 
COMMIT TRANSACTION
go
-- THÊM THÔNG BÁO XEM NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('ADD_THONGBAOXEMNHABAN_NHOMNHANVIEN','P') is not null
	drop proc ADD_THONGBAOXEMNHABAN_NHOMNHANVIEN
GO
create proc ADD_THONGBAOXEMNHABAN_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5), 
	@MANV CHAR(5),  
	@MANHABAN CHAR(5), 
	@MACHINHANH CHAR(5), 
	@NGAYXEM DATETIME, 
	@NHANXET NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH

INSERT INTO THONGBAOXEMNHA VALUES(@MAKHACHHANG, @MANV, NULL, @MANHABAN, @MACHINHANH, @NGAYXEM, @NHANXET)
COMMIT TRANSACTION
go

-- THÊM BẢNG THÔNG BÁO XEM NHÀ THUÊ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('ADD_THONGBAOXEMNHATHUE_NHOMNHANVIEN','P') is not null
	drop proc ADD_THONGBAOXEMNHATHUE_NHOMNHANVIEN
GO
create proc ADD_THONGBAOXEMNHATHUE_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5), 
	@MANV CHAR(5),  
	@MANHATHUE CHAR(5), 
	@MACHINHANH CHAR(5), 
	@NGAYXEM DATETIME, 
	@NHANXET NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHATHUE)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO THONGBAOXEMNHA VALUES(@MAKHACHHANG, @MANV, @MANHATHUE, NULL,  @MACHINHANH, @NGAYXEM, @NHANXET)
COMMIT TRANSACTION
go

--XÓA BẢNG THÔNG BÁO XEM NHÀ THUÊ
if OBJECT_ID ('DELETE_THONGBAOXEMNHATHUE_NHOMNHANVIEN','P') is not null
	drop proc DELETE_THONGBAOXEMNHATHUE_NHOMNHANVIEN
GO
create proc DELETE_THONGBAOXEMNHATHUE_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5), 
	@MANV CHAR(5),  
	@NGAYXEM DATETIME,
	@MANHATHUE CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM THONGBAOXEMNHA WHERE NGAYXEM = @NGAYXEM)
	BEGIN
		PRINT N'NGÀY XEM NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHATHUE)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM THONGBAOXEMNHA WHERE MAKHACHHANG = @MAKHACHHANG AND MANV = @MANV AND NGAYXEM = @NGAYXEM
COMMIT TRANSACTION
GO

--XÓA BẢNG THÔNG BÁO XEM NHÀ BÁN
if OBJECT_ID ('DELETE_THONGBAOXEMNHABAN_NHOMNHANVIEN','P') is not null
	drop proc DELETE_THONGBAOXEMNHABAN_NHOMNHANVIEN
GO
create proc DELETE_THONGBAOXEMNHABAN_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5), 
	@MANV CHAR(5),  
	@NGAYXEM DATETIME,
	@MANHABAN CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM THONGBAOXEMNHA WHERE NGAYXEM = @NGAYXEM)
	BEGIN
		PRINT N'NGÀY XEM NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM THONGBAOXEMNHA WHERE MAKHACHHANG = @MAKHACHHANG AND MANV = @MANV AND NGAYXEM = @NGAYXEM
COMMIT TRANSACTION
go

-- SỬA BẢNG THÔNG BÁO XEM NHÀ MÀ NHÀ THUỘC LOẠI NHÀ THUÊ
if OBJECT_ID ('UPDATE_THONGBAOXEMNHATHUE_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_THONGBAOXEMNHATHUE_NHOMNHANVIEN
GO
create proc UPDATE_THONGBAOXEMNHATHUE_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5),
	@MANV CHAR(5),
	@MANHATHUE CHAR(5),
	@MACHINHANH CHAR(5),
	@NGAYXEM DATETIME, 
	@NHANXET NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHATHUE)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_THONGBAOXEMNHATHUE_NHOMNHANVIEN @MAKHACHHANG, @MANV, @NGAYXEM, @MANHATHUE
	EXEC ADD_THONGBAOXEMNHATHUE_NHOMNHANVIEN @MAKHACHHANG, @MANV, @MANHATHUE, @MACHINHANH, @NGAYXEM, @NHANXET
COMMIT TRANSACTION
go

-- SỬA BẢNG THÔNG BÁO XEM NHÀ MÀ NHÀ THUỘC LOẠI NHÀ BÁN
if OBJECT_ID ('UPDATE_THONGBAOXEMNHABAN_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_THONGBAOXEMNHABAN_NHOMNHANVIEN
GO
create proc UPDATE_THONGBAOXEMNHABAN_NHOMNHANVIEN 
	@MAKHACHHANG CHAR(5),
	@MANV CHAR(5),
	@MANHABAN CHAR(5),
	@MACHINHANH CHAR(5),
	@NGAYXEM DATETIME, 
	@NHANXET NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_THONGBAOXEMNHABAN_NHOMNHANVIEN @MAKHACHHANG, @MANV, @NGAYXEM, @MANHABAN
	EXEC ADD_THONGBAOXEMNHABAN_NHOMNHANVIEN @MAKHACHHANG, @MANV, @MANHABAN, @MACHINHANH, @NGAYXEM, @NHANXET
COMMIT TRANSACTION
go

--2/
-- Ý 1	
--TÌM CHI NHÁNH TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('FIND_CHINHANH_NHOMNHANVIEN','P') is not null
	drop proc FIND_CHINHANH_NHOMNHANVIEN
GO
create proc FIND_CHINHANH_NHOMNHANVIEN  
	@MACHINHANH CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	SELECT *FROM CHINHANH WHERE MACHINHANH = @MACHINHANH
COMMIT TRANSACTION
go

--XEM CHI NHÁNH TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_CHINHANH_NHOMNHANVIEN','P') is not null
	drop proc VIEW_CHINHANH_NHOMNHANVIEN
GO
create proc VIEW_CHINHANH_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
	SELECT *FROM CHINHANH 
COMMIT TRANSACTION
go

--3--
--TÌM NHÀ BÁN TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('FIND_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc FIND_NHABAN_NHOMNHANVIEN
GO
create proc FIND_NHABAN_NHOMNHANVIEN  
	@MANHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	SELECT *FROM NHABAN WHERE MANHA = @MANHA
COMMIT TRANSACTION
go


--XEM BẢNG NHÀ BÁN TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('VIEW_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc VIEW_NHABAN_NHOMNHANVIEN
GO
create proc VIEW_NHABAN_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
	SELECT *FROM NHABAN 
COMMIT TRANSACTION
go


--TÌM NHÀ CHO THUÊ TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('FIND_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc FIND_NHACHOTHUE_NHOMNHANVIEN
GO
create proc FIND_NHACHOTHUE_NHOMNHANVIEN  
	@MANHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	SELECT *FROM NHACHOTHUE WHERE MANHA = @MANHA
COMMIT TRANSACTION
go

--XEM BẢNG NHÀ CHO THUÊ TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('VIEW_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc VIEW_NHACHOTHUE_NHOMNHANVIEN
GO
create proc VIEW_NHACHOTHUE_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
	SELECT *FROM NHACHOTHUE 
COMMIT TRANSACTION
go

--Ý 2
--THÊM 1 NHÀ TRONG BẢNG NHÀ BÁN Ở ROLE NHÂN VIÊN
if OBJECT_ID ('ADD_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc ADD_NHABAN_NHOMNHANVIEN
GO
create proc ADD_NHABAN_NHOMNHANVIEN
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT,
	@GIABAN INT,
	@DIEUKIENBAN NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
INSERT INTO NHABAN VALUES(@MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, @SOLUOTXEM, @GIABAN, @DIEUKIENBAN)
COMMIT TRANSACTION
go
EXEC ADD_NHABAN_NHOMNHANVIEN 'NB1', 'LN02', N'TP Hồ Chí Minh', 1, 'CN02', '001', 'CN01', '2017/10/15 00:00:00', '2018/10/15 00:00:00', N'TRỐNG', 1, 2000000, 'TRÊN 20T'
select *from NHABAN
select *from NHACHOTHUE
--THÊM 1 NHÀ TRONG BẢNG NHÀ CHO THUÊ Ở ROLE NHÂN VIÊN
if OBJECT_ID ('ADD_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc ADD_NHACHOTHUE_NHOMNHANVIEN
GO
create proc ADD_NHACHOTHUE_NHOMNHANVIEN
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@TIENTHUE1THANG INT,
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO NHACHOTHUE VALUES(@MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @TIENTHUE1THANG, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, 
@SOLUOTXEM)
COMMIT TRANSACTION
go

-- XÓA NHÀ BÁN TRONG ROLE NHÓM NHÂN VIÊN
if OBJECT_ID ('DELETE_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc DELETE_NHABAN_NHOMNHANVIEN
GO
create proc DELETE_NHABAN_NHOMNHANVIEN 
	@MANHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
DELETE FROM NHABAN WHERE MANHA = @MANHA
COMMIT TRANSACTION
go

-- XÓA NHÀ CHO THUÊ TRONG ROLE NHÓM NHÂN VIÊN
if OBJECT_ID ('DELETE_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc DELETE_NHACHOTHUE_NHOMNHANVIEN
GO
create proc DELETE_NHACHOTHUE_NHOMNHANVIEN 
	@MANHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
DELETE FROM NHACHOTHUE WHERE MANHA = @MANHA
COMMIT TRANSACTION
go

-- SỬA BẢNG NHÀ BÁN TRONG ROLE NHÓM NHÂN VIÊN
if OBJECT_ID ('UPDATE_NHABAN_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_NHABAN_NHOMNHANVIEN
GO
create proc UPDATE_NHABAN_NHOMNHANVIEN 
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT,
	@GIABAN INT,
	@DIEUKIENBAN NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END

END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_NHABAN_NHOMNHANVIEN @MANHA
	EXEC ADD_NHABAN_NHOMNHANVIEN @MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, @SOLUOTXEM, @GIABAN, @DIEUKIENBAN
COMMIT TRANSACTION
go

-- SỬA BẢNG NHÀ CHO THUÊ TRONG ROLE NHÓM NHÂN VIÊN
if OBJECT_ID ('UPDATE_NHACHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_NHACHOTHUE_NHOMNHANVIEN
GO
create proc UPDATE_NHACHOTHUE_NHOMNHANVIEN 
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@TIENTHUE1THANG INT,
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
		ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END

END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_NHACHOTHUE_NHOMNHANVIEN  @MANHA
	EXEC ADD_NHACHOTHUE_NHOMNHANVIEN @MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @TIENTHUE1THANG, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, 
@SOLUOTXEM
COMMIT TRANSACTION
go

-- TÌM 1 KHÁCH HÀNG TRONG ROLE ROLE NHÂN VIÊN 
if OBJECT_ID ('FIND_KHACHHANG_NHOMNHANVIEN','P') is not null
	drop proc FIND_KHACHHANG_NHOMNHANVIEN
GO
create proc FIND_KHACHHANG_NHOMNHANVIEN 
	@MANGUOITHUE CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	SELECT *FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE
COMMIT TRANSACTION
go

--XEM BẢNG KHÁCH HÀNG TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_KHACHHANG_NHOMNHANVIEN','P') is not null
	drop proc VIEW_KHACHHANG_NHOMNHANVIEN
GO
create proc VIEW_KHACHHANG_NHOMNHANVIEN 
AS
BEGIN TRANSACTION 

	SELECT *FROM KHACHHANG 
COMMIT TRANSACTION
go

--THÊM KHÁCH HÀNG VÀO BẢNG KHÁC HÀNG TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('ADD_KHACHHANG_NHOMNHANVIEN','P') is not null
	drop proc ADD_KHACHHANG_NHOMNHANVIEN
GO
create proc ADD_KHACHHANG_NHOMNHANVIEN 
	@MANGUOITHUE CHAR(5),
	@MALOAI CHAR(5),
	@HOTEN NVARCHAR(30),
	@DIACHI NVARCHAR(50),
	@SODIENTHOAI CHAR(12),
	@MACHINHANH CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT *FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT *FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO KHACHHANG VALUES(@MANGUOITHUE, @MALOAI, @HOTEN, @DIACHI, @SODIENTHOAI, @MACHINHANH)
COMMIT TRANSACTION
go

--XÓA KHÁCH HÀNG TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('DELETE_KHACHHANG_NHOMNHANVIEN','P') is not null
	drop proc DELETE_KHACHHANG_NHOMNHANVIEN
GO
create proc DELETE_KHACHHANG_NHOMNHANVIEN 
	@MANGUOITHUE CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE
COMMIT TRANSACTION
go

-- SỬA KHÁCH HÀNG TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('UPDATE_KHACHHANG_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_KHACHHANG_NHOMNHANVIEN
GO
create proc UPDATE_KHACHHANG_NHOMNHANVIEN 
	@MANGUOITHUE CHAR(5),
	@MALOAI CHAR(5),
	@HOTEN NVARCHAR(30),
	@DIACHI NVARCHAR(50),
	@SODIENTHOAI CHAR(12),
	@MACHINHANH CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MANGUOITHUE)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT *FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT *FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_KHACHHANG_NHOMNHANVIEN @MANGUOITHUE
	EXEC ADD_KHACHHANG_NHOMNHANVIEN @MANGUOITHUE, @MALOAI, @HOTEN, @DIACHI, @SODIENTHOAI, @MACHINHANH
COMMIT TRANSACTION
go

-- TÌM 1 HỢP ĐỒNG CHO THUÊ THÔNG QUA MÃ HỢP ĐỒNG TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('FIND_HOPDONGCHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc FIND_HOPDONGCHOTHUE_NHOMNHANVIEN
GO
create proc FIND_HOPDONGCHOTHUE_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT *FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG
COMMIT TRANSACTION
go

-- TÌM 1 HỢP ĐỒNG BÁN THÔNG QUA MÃ HỢP ĐỒNG TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('FIND_HOPDONGBAN_NHOMNHANVIEN','P') is not null
	drop proc FIND_HOPDONGBAN_NHOMNHANVIEN
GO
create proc FIND_HOPDONGBAN_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT *FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG
COMMIT TRANSACTION
go

-- XEM BẢNG HỢP ĐỒNG CHO THUÊ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_HOPDONGCHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc VIEW_HOPDONGCHOTHUE_NHOMNHANVIEN
GO
create proc VIEW_HOPDONGCHOTHUE_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
SELECT *FROM HOPDONGCHOTHUE
COMMIT TRANSACTION
go

-- XEM BẢNG HỢP ĐỒNG BÁN TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_HOPDONGBAN_NHOMNHANVIEN','P') is not null
	drop proc VIEW_HOPDONGBAN_NHOMNHANVIEN
GO
create proc VIEW_HOPDONGBAN_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
SELECT *FROM HOPDONGBAN
COMMIT TRANSACTION
go

--THÊM HỢP ĐỒNG CHO THUÊ TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('ADD_HOPDONGCHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc ADD_HOPDONGCHOTHUE_NHOMNHANVIEN
GO
create proc ADD_HOPDONGCHOTHUE_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5),
	@MANHACHOTHUE CHAR(5),
	@MAKHACHHANG CHAR(5),
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHACHOTHUE)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO HOPDONGCHOTHUE VALUES(@MAHOPDONG, @MANHACHOTHUE, @MAKHACHHANG, @MACHUNHA)
COMMIT TRANSACTION
go

--THÊM HỢP ĐỒNG BÁN TRONG ROLE NHÂN VIÊN 
if OBJECT_ID ('ADD_HOPDONGBAN_NHOMNHANVIEN','P') is not null
	drop proc ADD_HOPDONGBAN_NHOMNHANVIEN
GO
create proc ADD_HOPDONGBAN_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5),
	@MANHABAN CHAR(5),
	@MAKHACHHANG CHAR(5),
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF EXISTS(SELECT * FROM HOPDONGBAN WHERE MANHABAN = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY ĐÃ ĐƯỢC BÁN'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO HOPDONGBAN VALUES(@MAHOPDONG, @MANHABAN, @MAKHACHHANG, @MACHUNHA)
COMMIT TRANSACTION
go

-- XÓA HỢP ĐỒNG CHO THUÊ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('DELETE_HOPDONGCHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc DELETE_HOPDONGCHOTHUE_NHOMNHANVIEN
GO
create proc DELETE_HOPDONGCHOTHUE_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG
COMMIT TRANSACTION
go

-- XÓA HỢP ĐỒNG BÁN TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('DELETE_HOPDONGBAN_NHOMNHANVIEN','P') is not null
	drop proc DELETE_HOPDONGBAN_NHOMNHANVIEN
GO
create proc DELETE_HOPDONGBAN_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG
COMMIT TRANSACTION
go

--SỬA HỢP ĐỒNG CHO THUÊ 
if OBJECT_ID ('UPDATE_HOPDONGCHOTHUE_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_HOPDONGCHOTHUE_NHOMNHANVIEN
GO
create proc UPDATE_HOPDONGCHOTHUE_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5),
	@MANHACHOTHUE CHAR(5),
	@MAKHACHHANG CHAR(5),
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGCHOTHUE WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHACHOTHUE)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_HOPDONGCHOTHUE_NHOMNHANVIEN @MAHOPDONG
	EXEC ADD_HOPDONGCHOTHUE_NHOMNHANVIEN @MAHOPDONG, @MANHACHOTHUE, @MAKHACHHANG, @MACHUNHA
COMMIT TRANSACTION
go

--SỬA HỢP ĐỒNG BÁN
if OBJECT_ID ('UPDATE_HOPDONGBAN_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_HOPDONGBAN_NHOMNHANVIEN
GO
create proc UPDATE_HOPDONGBAN_NHOMNHANVIEN  
	@MAHOPDONG CHAR(5),
	@MANHABAN CHAR(5),
	@MAKHACHHANG CHAR(5),
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM HOPDONGBAN WHERE MAHOPDONG = @MAHOPDONG)
	BEGIN
		PRINT N'HỢP ĐỒNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHABAN)
	BEGIN
		PRINT N'NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE MANGUOITHUE = @MAKHACHHANG)
	BEGIN
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'LỖI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_HOPDONGBAN @MAHOPDONG
	EXEC ADD_HOPDONGBAN @MAHOPDONG, @MANHABAN, @MAKHACHHANG, @MACHUNHA
COMMIT TRANSACTION
go

--TÌM CHỦ NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('FIND_CHUNHA_NHOMNHANVIEN','P') is not null
	drop proc FIND_CHUNHA_NHOMNHANVIEN
GO
create proc FIND_CHUNHA_NHOMNHANVIEN  
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT *FROM CHUNHA WHERE MACHUNHA = @MACHUNHA
COMMIT TRANSACTION
go

--XEM BẢNG CHỦ NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('VIEW_CHUNHA_NHOMNHANVIEN','P') is not null
	drop proc VIEW_CHUNHA_NHOMNHANVIEN
GO
create proc VIEW_CHUNHA_NHOMNHANVIEN  
AS
BEGIN TRANSACTION 
	SELECT *FROM CHUNHA 
COMMIT TRANSACTION
go

--THÊM CHỦ NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('ADD_CHUNHA_NHOMNHANVIEN','P') is not null
	drop proc ADD_CHUNHA_NHOMNHANVIEN
GO
create proc ADD_CHUNHA_NHOMNHANVIEN  
	@MACHUNHA CHAR(5),
	@HOTEN NVARCHAR(50),
	@DIACHI NVARCHAR(50),
	@SODIENTHOAI CHAR(12)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY ĐÃ TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'CHỦ NHÀ NÀY ĐÃ TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	INSERT INTO CHUNHA VALUES(@MACHUNHA, @HOTEN, @DIACHI, @SODIENTHOAI)
COMMIT TRANSACTION
go

--XÓA CHỦ NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('DELETE_CHUNHA_NHOMNHANVIEN','P') is not null
	drop proc DELETE_CHUNHA_NHOMNHANVIEN
GO
create proc DELETE_CHUNHA_NHOMNHANVIEN  
	@MACHUNHA CHAR(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	DELETE FROM CHUNHA WHERE MACHUNHA = @MACHUNHA
COMMIT TRANSACTION
go

--SỬA CHỦ NHÀ TRONG ROLE NHÂN VIÊN
if OBJECT_ID ('UPDATE_CHUNHA_NHOMNHANVIEN','P') is not null
	drop proc UPDATE_CHUNHA_NHOMNHANVIEN
GO
create proc UPDATE_CHUNHA_NHOMNHANVIEN  
	@MACHUNHA CHAR(5),
	@HOTEN NVARCHAR(50),
	@DIACHI NVARCHAR(50),
	@SODIENTHOAI CHAR(12)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'CHỦ NHÀ NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	EXEC DELETE_CHUNHA_NHOMNHANVIEN @MACHUNHA
	EXEC ADD_CHUNHA_NHOMNHANVIEN @MACHUNHA, @HOTEN, @DIACHI, @SODIENTHOAI
COMMIT TRANSACTION
go

--TÌM NHÂN VIÊN 
if OBJECT_ID ('FIND_NHANVIEN_NHOMNHANVIEN','P') is not null
	drop proc FIND_NHANVIEN_NHOMNHANVIEN
GO
create proc FIND_NHANVIEN_NHOMNHANVIEN  
	@MANV CHAR(10)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
END TRY 
BEGIN CATCH
	PRINT N'NHÂN VIÊN NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
	SELECT *FROM NHANVIEN WHERE MANV = @MANV
COMMIT TRANSACTION
go
-- XEM BẢNG NHÂN VIÊN
if OBJECT_ID ('VIEW_NHANVIEN_NHOMNHANVIEN','P') is not null
	drop proc VIEW_NHANVIEN_NHOMNHANVIEN
GO
create proc VIEW_NHANVIEN_NHOMNHANVIEN  
AS
BEGIN TRANSACTION
	SELECT *FROM NHANVIEN
COMMIT TRANSACTION
go
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------PHÂN HỆ KHÁCH HÀNG----------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--khách hàng xem bảng thông báo xem nhà (chỉ xem dòng có mã KH của mình)
if OBJECT_ID ('VIEW_TABLE_THONGBAOXEMNHA_ROLEKH','P') is not null
	drop proc VIEW_TABLE_THONGBAOXEMNHA_ROLEKH
GO
create proc VIEW_TABLE_THONGBAOXEMNHA_ROLEKH  
AS
BEGIN TRANSACTION 
	--Lấy mã khách hàng từ tên đăng nhập và lưu vào biến @a
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra mã khách hàng có tồn tại trong bảng
	IF NOT EXISTS (SELECT MAKHACHHANG FROM THONGBAOXEMNHA WHERE MAKHACHHANG = @a) 
	begin
		PRINT N'BẠN KHÔNG CÓ THÔNG BÁO NÀO'
		ROLLBACK TRANSACTION
		RETURN
	end
END TRY
BEGIN CATCH
	PRINT N'BẠN KHÔNG CÓ THÔNG BÁO NÀO'
	ROLLBACK TRANSACTION
END CATCH
SELECT * FROM THONGBAOXEMNHA WHERE MAKHACHHANG = @a
COMMIT TRANSACTION
go

--khách hàng xem bảng bán nhà (với loại nhà mình yêu cầu)
if OBJECT_ID ('VIEW_TABLE_NHABAN_ROLEKH','P') is not null
	drop proc VIEW_TABLE_NHABAN_ROLEKH
GO
create proc VIEW_TABLE_NHABAN_ROLEKH  
	@loainha char(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	--Kiểm tra mã loại nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MALOAI FROM NHABAN WHERE MALOAI = @loainha) 
	begin
		PRINT N'KHÔNG CÓ LOẠI NHÀ BẠN YÊU CẦU'
		ROLLBACK TRANSACTION
		RETURN
	end
END TRY
BEGIN CATCH
	PRINT N'KHÔNG CÓ LOẠI NHÀ BẠN YÊU CẦU'
	ROLLBACK TRANSACTION
END CATCH
SELECT * FROM NHABAN WHERE MALOAI = @loainha
COMMIT TRANSACTION
go

--khách hàng xem bảng nhà cho thuê (với loại nhà mình yêu cầu)
if OBJECT_ID ('VIEW_TABLE_NHACHOTHUE_ROLEKH','P') is not null
	drop proc VIEW_TABLE_NHACHOTHUE_ROLEKH
GO
create proc VIEW_TABLE_NHACHOTHUE_ROLEKH  
	@loainha char(5)
AS
BEGIN TRANSACTION 
BEGIN TRY
	--Kiểm tra mã loại nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MALOAI FROM NHACHOTHUE WHERE MALOAI = @loainha) 
	begin
		PRINT N'KHÔNG CÓ LOẠI NHÀ BẠN YÊU CẦU'
		ROLLBACK TRANSACTION
		RETURN
	end
END TRY
BEGIN CATCH
	PRINT N'KHÔNG CÓ LOẠI NHÀ BẠN YÊU CẦU'
	ROLLBACK TRANSACTION
END CATCH
SELECT * FROM NHACHOTHUE WHERE MALOAI = @loainha
COMMIT TRANSACTION
go

--khách hàng xem bảng loại nhà 
if OBJECT_ID ('VIEW_TABLE_LOAINHA_ROLEKH','P') is not null
	drop proc VIEW_TABLE_LOAINHA_ROLEKH
GO
create proc VIEW_TABLE_LOAINHA_ROLEKH  
AS
BEGIN TRANSACTION 
	SELECT * FROM LOAINHA 
COMMIT TRANSACTION
go

--khách hàng xem bảng hợp đồng cho thuê (chỉ xem dòng có mã KH của mình)
if OBJECT_ID ('VIEW_TABLE_HOPDONGCHOTHUE_ROLEKH','P') is not null
	drop proc VIEW_TABLE_HOPDONGCHOTHUE_ROLEKH
GO
create proc VIEW_TABLE_HOPDONGCHOTHUE_ROLEKH  
AS
BEGIN TRANSACTION 
	--Lấy mã khách hàng từ tên đăng nhập và lưu vào biến @a
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra mã khách hàng có tồn tại trong bảng
	IF NOT EXISTS (SELECT MAKHACHHANG FROM HOPDONGCHOTHUE WHERE MAKHACHHANG = @a) 
	begin
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	end
END TRY
BEGIN CATCH
	PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT * FROM HOPDONGCHOTHUE WHERE MAKHACHHANG = @a
COMMIT TRANSACTION
go

--khách hàng xem bảng hợp đồng bán nhà (chỉ xem dòng có mã KH của mình)
if OBJECT_ID ('VIEW_TABLE_HOPDONGBAN_ROLEKH','P') is not null
	drop proc VIEW_TABLE_HOPDONGBAN_ROLEKH
GO
create proc VIEW_TABLE_HOPDONGBAN_ROLEKH  
AS
BEGIN TRANSACTION 
	--Lấy mã khách hàng từ tên đăng nhập và lưu vào biến @a
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra mã khách hàng có tồn tại trong bảng
	IF NOT EXISTS (SELECT MAKHACHHANG FROM HOPDONGBAN WHERE MAKHACHHANG = @a) 
	begin
		PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	end
END TRY
BEGIN CATCH
	PRINT N'KHÁCH HÀNG NÀY KHÔNG TỒN TẠI'
	ROLLBACK TRANSACTION
END CATCH
SELECT * FROM HOPDONGBAN WHERE MAKHACHHANG = @a
COMMIT TRANSACTION
go

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------PHÂN HỆ CHỦ NHÀ-------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--chủ nhà xem bảng nhà bán
if OBJECT_ID ('VIEW_TABLE_NHABAN_ROLECN','P') is not null
	drop proc VIEW_TABLE_NHABAN_ROLECN
GO
create proc VIEW_TABLE_NHABAN_ROLECN  
AS
BEGIN TRANSACTION 
SELECT * FROM NHABAN 
COMMIT TRANSACTION
go

--chủ nhà thêm vào bảng nhà bán 
if OBJECT_ID ('ADD_ROW_CHUNHA_NHABAN','P') is not null
	drop proc ADD_ROW_CHUNHA_NHABAN
GO
create proc ADD_ROW_CHUNHA_NHABAN 
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT,
	@GIABAN INT,
	@DIEUKIENBAN NVARCHAR(30)
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM NHABAN WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY ĐANG ĐƯỢC BÁN'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	INSERT INTO NHABAN VALUES(@MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, @SOLUOTXEM, @GIABAN, @DIEUKIENBAN)
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go

--chủ nhà xem bảng nhà thuê 
if OBJECT_ID ('VIEW_TABLE_NHATHUE_ROLECN','P') is not null
	drop proc VIEW_TABLE_NHATHUE_ROLECN
GO
create proc VIEW_TABLE_NHATHUE_ROLECN  
AS
BEGIN TRANSACTION 
SELECT * FROM NHACHOTHUE 
COMMIT TRANSACTION
go
exec VIEW_TABLE_NHATHUE_ROLECN

--chủ nhà thêm vào bảng nhà thuê
if OBJECT_ID ('ADD_ROW_CHUNHA_NHATHUE','P') is not null
	drop proc ADD_ROW_CHUNHA_NHATHUE
GO
create proc ADD_ROW_CHUNHA_NHATHUE 
	@MANHA CHAR(5),
	@MALOAI CHAR(5),
	@DIACHI NVARCHAR(50),
	@SOLUONGPHONG INT,
	@MACHINHANH CHAR(5),
	@MANVPHUTRACH CHAR(5),
	@MACHUNHA CHAR(5),
	@TIENTHUE1THANG INT,
	@NGAYDANG DATETIME,
	@NGAYHETHAN DATETIME,
	@TINHTRANG NVARCHAR(30),
	@SOLUOTXEM INT
AS
BEGIN TRANSACTION 
BEGIN TRY
	IF EXISTS(SELECT * FROM NHACHOTHUE WHERE MANHA = @MANHA)
	BEGIN
		PRINT N'NHÀ NÀY ĐÃ ĐƯỢC ĐĂNG'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM LOAINHA WHERE MALOAINHA = @MALOAI)
	BEGIN
		PRINT N'LOẠI NHÀ KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHINHANH WHERE MACHINHANH = @MACHINHANH)
	BEGIN
		PRINT N'CHI NHÁNH KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANVPHUTRACH)
	BEGIN
		PRINT N'NHÂN VIÊN KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	ELSE IF NOT EXISTS(SELECT * FROM CHUNHA WHERE MACHUNHA = @MACHUNHA)
	BEGIN
		PRINT N'CHỦ NHÀ KHÔNG TỒN TẠI'
		ROLLBACK TRANSACTION
		RETURN
	END
	INSERT INTO NHACHOTHUE VALUES(@MANHA, @MALOAI, @DIACHI, @SOLUONGPHONG, @MACHINHANH, @MANVPHUTRACH, @MACHUNHA, @TIENTHUE1THANG, @NGAYDANG, @NGAYHETHAN, @TINHTRANG, @SOLUOTXEM)
END TRY 
BEGIN CATCH
	PRINT N'LÕI NHẬP LIỆU'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go

--chủ nhà xóa nhà đã đăng bán
if OBJECT_ID ('DELETE_TABLE_NHABAN_ROLECN','P') is not null
	drop proc DELETE_TABLE_NHABAN_ROLECN
GO
create proc DELETE_TABLE_NHABAN_ROLECN  
	@MaNha char(5)
AS
BEGIN TRANSACTION 
	--Lấy mã chủ nhà từ tên đăng nhập và lưu vào biến @a
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra chủ nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MACHUNHA FROM NHABAN WHERE MACHUNHA = @a) 
	begin
		PRINT N'BẠN CHƯA ĐĂNG BÁN CĂN NHÀ NÀO'
		ROLLBACK TRANSACTION
		RETURN
	end
	--kiểm tra chủ nhà có muốn xóa đúng căn nhà mình đã đăng
	IF NOT EXISTS (SELECT MACHUNHA FROM NHABAN WHERE MACHUNHA = @a and MANHA=@MaNha) 
	begin
		PRINT N'CĂN NHÀ NÀY KHÔNG THUỘC SỞ HỮU CỦA BẠN'
		ROLLBACK TRANSACTION
		RETURN
	end
	DELETE FROM NHABAN WHERE MANHA = @MaNha
	PRINT N'XÓA THÀNH CÔNG'
END TRY
BEGIN CATCH
	PRINT N'LỖI KHÔNG THỂ XÓA'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go

--chủ nhà xóa nhà đã cho thuê
if OBJECT_ID ('DELETE_TABLE_NHACHOTHUE_ROLECN','P') is not null
	drop proc DELETE_TABLE_NHACHOTHUE_ROLECN
GO
create proc DELETE_TABLE_NHACHOTHUE_ROLECN  
	@MaNha char(5)
AS
BEGIN TRANSACTION 
	--Lấy mã chủ nhà từ tên đăng nhập và lưu vào biến @a
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra chủ nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MACHUNHA FROM NHACHOTHUE WHERE MACHUNHA = @a) 
	begin
		PRINT N'BẠN CHƯA CHO THUÊ CĂN NHÀ NÀO'
		ROLLBACK TRANSACTION
		RETURN
	end
	--kiểm tra chủ nhà có muốn xóa đúng căn nhà mình đã đăng
	IF NOT EXISTS (SELECT MACHUNHA FROM NHACHOTHUE WHERE MACHUNHA = @a and MANHA=@MaNha) 
	begin
		PRINT N'CĂN NHÀ NÀY KHÔNG THUỘC SỞ HỮU CỦA BẠN'
		ROLLBACK TRANSACTION
		RETURN
	end
	DELETE FROM NHACHOTHUE WHERE MANHA = @MaNha
	PRINT N'XÓA THÀNH CÔNG'
END TRY
BEGIN CATCH
	PRINT N'LỖI KHÔNG THỂ XÓA'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go

--chủ nhà xem bảng thông báo xem nhà
if OBJECT_ID ('VIEW_TABLE_THONGBAOXEMNHA_ROLECN','P') is not null
	drop proc VIEW_TABLE_THONGBAOXEMNHA_ROLECN
GO
create proc VIEW_TABLE_THONGBAOXEMNHA_ROLECN  
AS
BEGIN TRANSACTION 
SELECT * FROM THONGBAOXEMNHA 
COMMIT TRANSACTION
go

--chủ nhà xem bảng hợp đồng bán nhà
if OBJECT_ID ('VIEW_TABLE_HOPDONGBAN_ROLECN','P') is not null
	drop proc VIEW_TABLE_HOPDONGBAN_ROLECN
GO
create proc VIEW_TABLE_HOPDONGBAN_ROLECN  
AS
BEGIN TRANSACTION 
	--Lấy mã chủ nhà từ tên đăng nhập	
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra mã chủ nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MACHUNHA FROM HOPDONGBAN WHERE MACHUNHA = @a) 
	begin
		PRINT N'BẠN KHÔNG CÓ HỢP ĐỒNG NÀO'
		ROLLBACK TRANSACTION
		RETURN
	end
	SELECT * FROM HOPDONGBAN WHERE MACHUNHA = @a
END TRY
BEGIN CATCH
	PRINT N'BẠN KHÔNG CÓ THÔNG BÁO NÀO'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go

if OBJECT_ID ('VIEW_TABLE_HOPDONGCHOTHUE_ROLECN','P') is not null
	drop proc VIEW_TABLE_HOPDONGCHOTHUE_ROLECN
GO
create proc VIEW_TABLE_HOPDONGCHOTHUE_ROLECN  
AS
BEGIN TRANSACTION 
	--Lấy mã chủ nhà từ tên đăng nhập	
	declare @a varchar(10)
	set @a = (SELECT name FROM master.sys.sql_logins where name = ORIGINAL_LOGIN())
BEGIN TRY
	--Kiểm tra mã chủ nhà có tồn tại trong bảng
	IF NOT EXISTS (SELECT MACHUNHA FROM HOPDONGCHOTHUE WHERE MACHUNHA = @a) 
	begin
		PRINT N'BẠN KHÔNG CÓ HỢP ĐỒNG NÀO'
		ROLLBACK TRANSACTION
		RETURN
	end
	SELECT * FROM HOPDONGCHOTHUE WHERE MACHUNHA = @a
END TRY
BEGIN CATCH
	PRINT N'BẠN KHÔNG CÓ THÔNG BÁO NÀO'
	ROLLBACK TRANSACTION
END CATCH
COMMIT TRANSACTION
go